-- ========================================================
-- Script DDL: Dominio de Usuarios (DigitalFix IDaaS)
-- Subissue 2: Estructura de tablas y restricciones
-- ========================================================

-- 1. TABLA DE EMPRESAS (PyMEs de la Red)
CREATE TABLE EMPRESAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_EMPRESAS PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(150) NOT NULL,
    RUT VARCHAR2(12) NOT NULL CONSTRAINT UK_EMPRESA_RUT UNIQUE,
    TIPO_EMPRESA VARCHAR2(50) DEFAULT 'FIELD_SERVICE',
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. TABLA DE ROLES
CREATE TABLE ROLES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_ROLES PRIMARY KEY,
    CODIGO VARCHAR2(30) NOT NULL CONSTRAINT UK_ROL_CODIGO UNIQUE,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(255)
);

-- 3. TABLA DE USUARIOS (Con Restricciones FK y Unique)
CREATE TABLE USUARIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_USUARIOS PRIMARY KEY,
    USER_ENTRA_ID VARCHAR2(100) NOT NULL CONSTRAINT UK_USUARIO_ENTRA_ID UNIQUE, -- Sub/OID de Entra ID
    EMAIL VARCHAR2(100) NOT NULL CONSTRAINT UK_USUARIO_EMAIL UNIQUE,             -- Correo Único
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    TELEFONO VARCHAR2(20),
    AREA VARCHAR2(80),
    ID_EMPRESA NUMBER NOT NULL,
    ID_ROL NUMBER NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    -- Definición explícita de llaves foráneas
    CONSTRAINT FK_USUARIO_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID)
);

-- 4. ÍNDICES DE RENDIMIENTO (Para búsquedas rápidas tras el login)
CREATE INDEX IDX_USUARIO_ENTRA_ID ON USUARIOS(USER_ENTRA_ID);
CREATE INDEX IDX_USUARIO_EMAIL ON USUARIOS(EMAIL);

-- 5. DATOS SEMILLA BASE PARA ROLES
INSERT INTO ROLES (CODIGO, NOMBRE, DESCRIPCION) VALUES ('ADMIN', 'Administrador General', 'Acceso completo al sistema de la PyME');
INSERT INTO ROLES (CODIGO, NOMBRE, DESCRIPCION) VALUES ('SUPERVISOR', 'Supervisor de Campo', 'Gestión de cuadrillas de trabajo');
INSERT INTO ROLES (CODIGO, NOMBRE, DESCRIPCION) VALUES ('TECNICO', 'Técnico Electromecánico', 'Ejecutor de pautas en terreno');
INSERT INTO ROLES (CODIGO, NOMBRE, DESCRIPCION) VALUES ('CLIENTE', 'Cliente Final / Inmueble', 'Visualizador de reportes y solicitudes');

COMMIT;